/**
 * Docs source loader — wraps fumadocs-mdx's loader against the
 * Fumadocs-managed `.source` directory.
 *
 * The compiled doc tree is generated by `fumadocs-mdx` at build time
 * from the synced `content/docs/` (populated by `scripts/sync-content.mjs`).
 * Pages and components consume this loader to render trees, walk
 * the registry, and look up individual specs by slug.
 */

import { loader } from "fumadocs-core/source"
import { docs } from "@/../.source"

export const docsSource = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
})
